#!/bin/bash

set -e

usage(){
	echo "Usage: $0 gap_userid"
	exit 1
}

[[ $# -eq 0 ]] && usage

userid=${1}

chmod 400 config/id_rsa_jb config/pcf

. .venv/bin/activate

# enter local workstation password to update sudo timer
sudo -v

check_success(){
    if [[ $? -eq 0 ]]; then
        echo "Connected to ${1}"
    else
        echo "Failed to connect to ${1}"
    fi
}

if curl -s -k --connect-timeout 5 https://10.107.48.22:25555 1>/dev/null; then
    echo "Connected to PCI shuttle"
else
         echo "Connecting to PCI shuttle..."
         sshuttle -D --pidfile /tmp/shuttle_pci.pid --dns --remote=${userid}@pci_inner 10.107.0.0/16 \
         --ssh-cmd 'ssh -F config/ssh_config' \
         -x 10.107.32.0/24 \
         -x 10.107.40.0/21 \
         -x 10.107.34.0/23 \
         -x 10.107.36.0/23 \
         -x 10.107.34.0/23
         check_success "PCI Shuttle" 
fi

if curl -s -k --connect-timeout 5 https://10.116.39.139:25555 1>/dev/null; then
    echo "Connected to Prod shuttle"
else
         echo "Connecting to Prod shuttle..."
         # cfdev-azw-mgmt - 10.116.55.128/25
         sshuttle -D --pidfile /tmp/shuttle_prod.pid --dns --remote=${userid}@prod_inner 10.116.39.128/25 10.116.40.0/22 10.116.55.128/25 \
         --ssh-cmd 'ssh -F config/ssh_config'
         check_success "Prod Shuttle"
fi

#sleep 5

if curl -s -k --connect-timeout 5 https://10.2.16.21:25555 1>/dev/null; then
    echo "Connected to general shuttle"
else
echo "Connecting to general shuttle..."
         sshuttle -D --pidfile /tmp/shuttle_general.pid --dns --remote=${userid}@sandbox_inner 10.0.0.0/8 \
         --ssh-cmd 'ssh -F config/ssh_config' \
         -x 10.240.1.0/24  \
         -x 10.107.48.0/24 \
         -x 10.107.80.0/21 \
         -x 10.107.50.0/23 \
         -x 10.107.52.0/23 \
         -x 10.116.39.128/25 \
         -x 10.116.40.0/22 \
         -x 10.116.55.128/25
         check_success "General Shuttle"
fi
