#!/bin/bash
set -e

if bosh --version |grep BOSH; then
    echo "Please switch from bosh v1 to bosh v2"
    exit
fi

SCRIPTDIR=$(dirname $0)

echo "logging into ${BOSH_IP:?}" >&2
bosh login -e ${BOSH_ENVIRONMENT}
