#!/bin/bash

set -e

SCRIPTDIR=$(dirname $0)

[[ -d deployments ]] || {
  echo "I do not know how to operate outside of the base of the working directory" >&2
  echo "try navigating to $SCRIPTDIR/../.."
  exit 1
}

scripts/bosh/login

deployments=$(scripts/bosh/curl /deployments --insecure --silent | jq '.[].name' --raw-output)

for deployment in $deployments; do
  bosh manifest -d $deployment > deployments/$deployment.yml
done
