#!/bin/bash

VCAP_PASSWORD=$(scripts/opsman/curl /api/v0/deployed/director/credentials/vm_credentials | jq --raw-output .credential.value.password)
echo "director's vcap password is ${VCAP_PASSWORD}" >&2

chmod 400 ./config/pcf
ssh -i ./config/pcf vcap@${BOSH_IP:?}
