#!/usr/bin/env ruby
require 'yaml'
#require 'pp'

yml = Dir.glob('deployments/cf-*.yml').first
if yml.nil?
  STDERR.puts "can not find deployments/cf-*.yml"
  exit 1
end

hash = YAML.load_file yml
job = hash["instance_groups"].find {|i| i['name']=='cloud_controller'}
ccdb = job['properties']['ccdb']
address = ccdb['address']
user = ccdb['roles'][0]['name']
password = ccdb['roles'][0]['password']

puts "-- login bosh..."
`./scripts/bosh/login`
puts "-- now please run:"
puts "./scripts/bosh/bosh_ssh -d #{yml} cloud_controller/0"
puts "-- then run:"
puts "if ! which mysql; then apt-get update; sudo apt-get install -y mysql-client; fi; mysql -h #{address} -u  #{user} -p#{password} ccdb"
