#!/usr/bin/env ruby
require 'yaml'
require 'pp'

yml = Dir.glob('deployments/cf-*.yml').first
if yml.nil?
  STDERR.puts "can not find deployments/cf-*.yml"
  exit 1
end

system('./scripts/cf/login -o cloudops -s cloudops')

hash = YAML.load_file yml
job = hash["instance_groups"].find {|i| i['name']=='uaa'}
users = job['properties']['uaa']['scim']['users']
users.each do |u|
  name = u['name']
  pwd = u['password']
  puts "== verify password for user #{name} ..."
  system("cf auth #{name} #{pwd}") || raise("wrong password for user #{name}")
end
