#!/bin/bash

BEARER_TOKEN=$(scripts/opsman/login)

curl "https://opsman.${CF_SYS_DOMAIN:?}/api/v0/stemcells" --form "stemcell[file]=@${1:?please specify stemcell filename}" -X POST --verbose --compressed --location --insecure --header "Authorization: Bearer ${BEARER_TOKEN:?}"
