#!/usr/bin/env ruby
require 'yaml'

@uuids = []

def filter_uuid (str)
  case str
  when /-partition-/
    _, job_name, uuid = str.match(/(.+)-partition-([0-9a-f]{20}$)/).to_a
    az = @uuids.index(uuid)
    if az.nil?
      @uuids << uuid
      az = @uuids.size
    else
      az += 1
    end

    job_name + "_z" + az.to_s
  else
    str.gsub(/(-[0-9a-f]{20}$)/, '')
  end
end

manifest = YAML.load(ARGF)

# filter the deployment name
manifest["name"] = filter_uuid(manifest["name"])

# filter the job names
manifest["jobs"].each do |job|
  job["name"] = filter_uuid(job["name"])
end

puts manifest.to_yaml
