#!/usr/bin/env ruby
require 'time'

`./scripts/cf/login -o cloudops -s cloudops`

spaces=`cf spaces | grep cloudops-smoke-tests_`
spaces.each_line do |s|
  m = s.match(/cloudops-smoke-tests_(201.*UTC)/).to_a[1]
  if m && (Time.now - Time.parse(m) > 3600 *4 )
    puts "-- deleting #{s}"
    `cf delete-space #{s} -f`
  end
end
